name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 安装 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 安装 python 包 依赖
        run: pip install -r requirements.txt
      - name: 创建 server 目录
        run: mkdir server
      - name: 下载 Minecraft Server Launcher
        run: wget -O server/fabric-server.jar https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.11/1.0.1/server/jar
      - name: 初始化服务器
        run: |
          cd server
          ${JAVA_HOME_21_X64}/bin/java -Xmx12G -jar fabric-server.jar nogui
          cd ..
      - name: 同意 EULA
        run: python scripts/Agree-EULA.py
      - name: 禁用 sync-chunk-writes
        run: python scripts/Disable-Sync-Chunk-Writes.py
      - name: 设置一个固定的种子
        run: python scripts/Set-Map-Seed.py
      - name: 设置 max-tick-time
        run: python scripts/Set-Max-Tick-Time.py
      - run: python scripts/Loop-OutPut.py &
      - name: 安装 carpet,spark,chunky 模组
        run: |
          wget -O server/mods/fabric-api-0.97.1+1.20.4.jar https://github.com/FabricMC/fabric/releases/download/0.97.1%2B1.20.4/fabric-api-0.97.1+1.20.4.jar
          wget -O server/mods/fabric-carpet-1.20.3-1.4.128+v231205.jar https://github.com/gnembon/fabric-carpet/releases/download/1.4.128/fabric-carpet-1.20.3-1.4.128+v231205.jar
          wget -O server/mods/spark-1.10.71-fabric.jar https://ci.lucko.me/job/spark/416/artifact/spark-fabric/build/libs/spark-1.10.71-fabric.jar
          wget -O server/mods/Chunky-1.3.146.jar https://cdn.modrinth.com/data/fALzjamp/versions/NHWYq9at/Chunky-1.3.146.jar
      - name: 创建 Benchmarks 目录
        run: mkdir Benchmarks
      - run: python scripts/Loop-OutPut.py &
      - run: python scripts/Loop-OutPut.py
      - name: 运行基准测试
        run: |
          python scripts/Loop-OutPut.py &
          python Benchmark.py
      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: Benchmarks/
      - name: 上传日志
        uses: actions/upload-artifact@v4
        with:
          name: Logs
          path: server/logs/
