name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 安装 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 安装 python 包 依赖
        run: python3 -m pip install -r requirements.txt
      - name: 创建 server 目录
        run: mkdir server
      - name: 下载 Minecraft Server Launcher
        run: wget -O server/fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.11/1.0.1/server/jar
      - name: 初始化服务器
        run: |
          cd server
          ${JAVA_HOME_21_X64}/bin/java -Xmx12G -jar fabric-server-mc.1.20.4-loader.0.15.11-launcher.1.0.1.jar nogui
          ls -a
          cd ..
      - name: 同意 EULA
        run: python3 scripts/Agree-EULA.py
      - name: 禁用 sync-chunk-writes
        run: python3 scripts/Disable-Sync-Chunk-Writes.py
